#!/bin/bash
                                                                              
# path to this directory
BASEDIR=$(dirname $0)

# compile the code
mkdir -p $BASEDIR/target/classes 
echo find $BASEDIR/src/main/java/ -iname *.java > files.txt
find $BASEDIR/src/main/java/ -iname *.java > files.txt
javac @files.txt -d $BASEDIR/target/classes
rm files.txt

# catch arguments

class=edu.tufts.cs.ml.learning.active.drivers.ActiveLearn
printUsage() {
    java -cp $BASEDIR/target/classes $class --USAGE
    exit
}

# mandatory arguments
if [[ "$1" != "" && "$2" != "" && "$3" != "" ]]; then
    if [[ "$@" == *--usage* ]]; then
        printUsage
    else
        train="$1"
        random="$2"
        uncertainty="$3"
    fi
else
    printUsage
    exit
fi

java -cp $BASEDIR/target/classes $class $train $random $uncertainty
