#!/bin/bash
                                                                              
# path to this directory
BASEDIR=$(dirname $0)

# compile the code
mkdir -p $BASEDIR/target/classes 
echo find $BASEDIR/src/main/java/ -iname *.java > files.txt
find $BASEDIR/src/main/java/ -iname *.java > files.txt
javac @files.txt -d $BASEDIR/target/classes
rm files.txt

# catch arguments

class=edu.tufts.cs.ml.cluster.drivers.ClusterWithKMeans
printUsage() {
    java -cp $BASEDIR/target/classes $class --USAGE
    exit
}

# mandatory arguments
if [[ "$1" != "" ]]; then
    if [[ "$@" == *--usage* ]]; then
        printUsage
    else
        dataset="$1"
    fi
else
    printUsage
    exit
fi

if [[ "$2" != "" ]]; then
    output="$2"
fi

java -cp $BASEDIR/target/classes $class $dataset $output
